<?php

/**
 * @file
 */

/**
 * Implements hook_help.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\Request;
use Drupal\Core\Database\Database;


/**
 *
 */
function pasarela_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {

      // Main module help for the block module.
    case 'help.page.pasarela':
      return '<p>Este es un hook_help TEsting</p>';

      // Help for another path in the block module.
    case 'block.admin_display':
      return '<p>' . t('This page provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions. Since not all themes implement the same regions, or display regions in the same way, blocks are positioned on a per-theme basis. Remember that your changes will not be saved until you click the <em>Save blocks</em> button at the bottom of the page.') . '</p>';
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert.
 */
function pasarela_node_insert(NodeInterface $node)
{
  dpm('Llama a nuestro insert nodo');
}

/**
 * Implements hook_ENTITY_TYPE_update.
 */
function pasarela_node_update(NodeInterface $node)
{
  dpm('Llama a nuestro update nodo');
}

/**
 * Implements hook_preprocess_HOOK() for block templates.
 */
function pasarela_preprocess_block(&$variables)
{
  // Check the region and hide it if needed
  //echo "entra";exit;
  /*echo "<pre>";
  echo "entra";
  var_dump($variables);
  echo "</pre>";exit;*/
  /*if ($variables['elements']['#region'] == 'sidebar_right') {
      $variables['content']['#markup'] = '';
  }*/

  //unset($variables['page']['page']['regions']['sidebar_right']);
}


/**
 * Implements hook_theme_suggestions_HOOK_alter() for page templates.
 */
function pasarela_theme_suggestions_page_alter(array &$suggestions, array $variables)
{
  // Add a suggestion for a custom template based on the page path
  $path = \Drupal::service('path.current')->getPath();
  if ($path == '/codeudores/list') {
    //echo "entra";exit;
    $suggestions[] = 'test';
  }
}

/**
 * Implements hook_theme.
 */
function pasarela_theme($existing, $type, $theme, $path)
{

  // dpm($existing);
  // dpm($type);
  // dpm($theme);
  // dpm($path);

  return [
    // "listado_reglas_redireccionamiento" => [
    //   'template' => 'reglasSoliCredito/reglasSoliCredito',
    //   'variables' => [
    //     'permisoVisualizacion' => '',
    //     'permisoCreacion' => '',
    //     'ruta' => ''
    //   ],
    // ],
    "archivos" => [
      'template' => 'archivos/cargueArchivo',
      'variables' => []
    ],
  ];
}

function pasarela_cron()
{
  $response = "Corrio";

  Drupal::messenger()->addMessage($response);
}
